version: "3.7"

services:
  backend:
    image: node:17-alpine
    working_dir: /app
    volumes:
      - ./back:/app
    ports:
      - "5000:5000"
    command: sh -c "yarn run start"

  frontend:
    image: node:17-alpine
    working_dir: /app
    volumes:
      - type: bind
        source: ./front
        target: /app
        volume:
          nocopy: true
    ports:
      - "3000:3000"
    command: sh -c "yarn run start"